ldev2pcs: do not attempt to set crypto settings under --dry-run
ldev2pcs attempts to change crypto-related settings in
/etc/corosync/corosync.conf for certain pacemaker versions.

This isn't done via run_cmd(), and so it is executed even when the user has
used the --dry-run option.  This may fail if the file doesn't exist,
with:

Traceback (most recent call last):
  File "./scripts/ldev2pcs", line 271, in <module>
    main()
  File "./scripts/ldev2pcs", line 268, in main
    configure()
  File "./scripts/ldev2pcs", line 164, in configure
    '/etc/corosync/corosync.conf'
  File "./scripts/ldev2pcs", line 48, in file_regex_replace
    f = open(path, 'r+')
IOError: [Errno 2] No such file or directory: '/etc/corosync/corosync.conf'

Correct this by checking the option before reading, altering, and rewriting the
file contents.

Signed-off-by: Olaf Faaland <faaland1@llnl.gov>